#version 430 core

struct Particle
{
    vec4 position;
    vec4 speed;
    float size;
    float _padding[3];
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer Particles
{
    Particle particles[];
};

uniform float u_delta_time;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    particles[idx].position.xyz += particles[idx].speed.xyz * u_delta_time;
    particles[idx].size = 0.25;
}
