void main()
{
    uint idx = gl_GlobalInvocationID.x;
    update(particles[idx], particles_velocity[idx], idx);
    particles[idx].position += particles_velocity[idx].position * u_delta_time;
    particles[idx].color += particles_velocity[idx].color * u_delta_time;
    particles[idx].size += particles_velocity[idx].size * u_delta_time;
    particles[idx].angle += particles_velocity[idx].angle * u_delta_time;
    particles[idx].life += particles_velocity[idx].life * u_delta_time;
}
